# Generated by Django 5.1.3 on 2025-04-27 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.CharField(blank=True, max_length=100)),
                ('exercise', models.CharField(blank=True, max_length=100)),
                ('food', models.CharField(blank=True, max_length=100)),
                ('sleep', models.CharField(blank=True, max_length=100)),
                ('mindfulness', models.CharField(blank=True, max_length=100)),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
